# Generated by Django 4.2.7 on 2024-01-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rosterId", models.PositiveIntegerField()),
                ("team", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                ("portraitId", models.PositiveIntegerField()),
                ("position", models.CharField(max_length=10)),
                ("lastSeasonPts", models.PositiveIntegerField()),
                ("drafted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "players",
                    models.ManyToManyField(related_name="teams", to="teams.player"),
                ),
            ],
        ),
    ]
