# Generated by Django 4.2.7 on 2024-01-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_weeklystat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="players",
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("QB", "Quarterback"),
                            ("RB1", "Running Back 1"),
                            ("RB2", "Running Back 2"),
                            ("WR1", "Wide Receiver 1"),
                            ("WR2", "Wide Receiver 2"),
                            ("TE", "Tight End"),
                            ("RQB", "Reserve Quarterback"),
                            ("RRB", "Reserve Running Back"),
                            ("RWR", "Reserve Wide Receiver"),
                            ("RTE", "Reserve Tight End"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="teams.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
