# Generated by Django 4.2.7 on 2024-01-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_players_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="losses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="totalPoints",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="wins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
