# Generated by Django 4.2.7 on 2024-02-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_team_losses_team_totalpoints_team_wins"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_round", models.IntegerField(default=1)),
                ("total_rounds", models.IntegerField(default=10)),
                ("direction", models.BooleanField(default=True)),
            ],
        ),
    ]
