# Generated by Django 5.0.4 on 2024-06-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='teams.team')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='teams.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
