# Generated by Django 5.0.4 on 2024-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_schedule_delete_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystat',
            name='passing_yards',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklystat',
            name='receiving_yards',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weeklystat',
            name='rushing_yards',
            field=models.FloatField(default=0.0),
        ),
    ]
