# Generated by Django 5.0.4 on 2024-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_weeklystat_passing_yards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draftPick',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
