# Generated by Django 5.0.4 on 2024-11-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_draftstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=0)),
                ('pick', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='teams.team')),
            ],
            options={
                'ordering': ['round', 'pick'],
                'unique_together': {('player',)},
            },
        ),
    ]
